name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    # Weekly run to catch HACS spec changes
    - cron: "0 0 * * 0"

jobs:
  hassfest:
    name: HA hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
